### ISSUE TITLE
Add gitlab application

### ISSUE THREAD

**Issue by chendelin1982** [websoft9dev/role_docker#12]
1. var: docker_apps_gitlab_port=["9090", "2224"]
2. compose.yml
```
# Refert to: https://docs.gitlab.com/omnibus/docker/#install-gitlab-using-docker-compose
version: "2.0"
services:
  gitlab:
      image: gitlab/gitlab-ee:latest
      container_name: "{{docker_appname}}"
      environment:
        GITLAB_OMNIBUS_CONFIG: |
          external_url 'http://127.0.0.1:{{docker_apps_gitlab_port[0]}}'
          gitlab_rails['gitlab_shell_ssh_port'] = 2224
      restart: always
      ports:
       - {{docker_apps_gitlab_port[0]}}:80
       - {{docker_apps_gitlab_port[1]}}:2224
      volumes:
       - "{{docker_apps_dir}}/{{docker_appname}}/config:/etc/gitlab"
       - "{{docker_apps_dir}}/{{docker_appname}}/logs:/var/log/gitlab"
       - "{{docker_apps_dir}}/{{docker_appname}}/data:/var/opt/gitlab"

networks:
  default:
    external:
      name: "{{docker_addnetwork}}"
```
